[0m23:00:34.302436 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7E286CE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7E340B920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7E243EA20>]}


============================== 23:00:34.343465 | ae376247-2519-420e-a4ce-307e9d9ccb3b ==============================
[0m23:00:34.343465 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:00:34.344465 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m23:00:54.347210 [debug] [MainThread]: Starter project path: C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\.venv\Lib\site-packages\dbt\include\starter_project
[0m23:00:54.367368 [info ] [MainThread]: 
Your new dbt project "dbt_northwind" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m23:00:54.367368 [info ] [MainThread]: Setting up your profile.
[0m23:02:47.611653 [info ] [MainThread]: Profile dbt_northwind written to C:\Users\Uso Pessoal\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m23:02:47.613842 [debug] [MainThread]: Command `dbt init` succeeded at 23:02:47.613842 after 133.56 seconds
[0m23:02:47.615231 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7E286CE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7E46F4800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F7E46F7800>]}
[0m23:02:47.616704 [debug] [MainThread]: Flushing usage events
[0m23:02:49.120408 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:03:07.173526 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BF8A25F3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BF8CEAD940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BF8D1ED970>]}


============================== 23:03:07.183225 | 5e3e00f6-c6c1-4d4b-bf0b-caaa2f3c77f0 ==============================
[0m23:03:07.183225 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:03:07.184196 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:03:07.250978 [info ] [MainThread]: dbt version: 1.9.8
[0m23:03:07.252023 [info ] [MainThread]: python version: 3.12.8
[0m23:03:07.252726 [info ] [MainThread]: python path: C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\.venv\Scripts\python.exe
[0m23:03:07.252726 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m23:03:07.344961 [info ] [MainThread]: Using profiles dir at C:\Users\Uso Pessoal\.dbt
[0m23:03:07.345968 [info ] [MainThread]: Using profiles.yml file at C:\Users\Uso Pessoal\.dbt\profiles.yml
[0m23:03:07.345968 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\dbt_project.yml
[0m23:03:07.347089 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m23:03:07.348089 [debug] [MainThread]: Command `dbt debug` failed at 23:03:07.348089 after 0.37 seconds
[0m23:03:07.349089 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BF8C9FF920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BF8EB1C0E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BF8D062BD0>]}
[0m23:03:07.349089 [debug] [MainThread]: Flushing usage events
[0m23:03:08.942027 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:09:18.607695 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CCF0BA65A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CCF330B6B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CCF2D70F50>]}


============================== 23:09:18.613197 | a78f1a5d-f382-4779-af25-577da752631a ==============================
[0m23:09:18.613197 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:09:18.614162 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:09:18.631172 [info ] [MainThread]: dbt version: 1.9.8
[0m23:09:18.632173 [info ] [MainThread]: python version: 3.12.8
[0m23:09:18.633168 [info ] [MainThread]: python path: C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\.venv\Scripts\python.exe
[0m23:09:18.633168 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m23:09:18.690399 [info ] [MainThread]: Using profiles dir at C:\Users\Uso Pessoal\.dbt
[0m23:09:18.691381 [info ] [MainThread]: Using profiles.yml file at C:\Users\Uso Pessoal\.dbt\profiles.yml
[0m23:09:18.692050 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\dbt_project.yml
[0m23:09:18.692570 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m23:09:18.693726 [debug] [MainThread]: Command `dbt debug` failed at 23:09:18.693726 after 0.29 seconds
[0m23:09:18.693726 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CCF353E0F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CCF2ED9070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CCF4D3B3B0>]}
[0m23:09:18.693726 [debug] [MainThread]: Flushing usage events
[0m23:09:19.688978 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:09:28.778572 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DA22F90AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DA1ED06390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DA231EBE30>]}


============================== 23:09:28.783622 | 3b78b18d-4e48-4b59-986f-8431fe5c5d7f ==============================
[0m23:09:28.783622 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:09:28.784611 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:09:28.798244 [info ] [MainThread]: dbt version: 1.9.8
[0m23:09:28.799239 [info ] [MainThread]: python version: 3.12.8
[0m23:09:28.799239 [info ] [MainThread]: python path: C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\.venv\Scripts\python.exe
[0m23:09:28.800489 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m23:09:28.855501 [info ] [MainThread]: Using profiles dir at C:\Users\Uso Pessoal\.dbt
[0m23:09:28.855501 [info ] [MainThread]: Using profiles.yml file at C:\Users\Uso Pessoal\.dbt\profiles.yml
[0m23:09:28.856489 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\dbt_project.yml
[0m23:09:28.857095 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m23:09:28.858359 [debug] [MainThread]: Command `dbt debug` failed at 23:09:28.858359 after 0.20 seconds
[0m23:09:28.858359 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DA2341F260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DA22B2BA70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DA231EBE30>]}
[0m23:09:28.858359 [debug] [MainThread]: Flushing usage events
[0m23:09:29.798909 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:10:33.814119 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257901136B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002578C7D09B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025790296900>]}


============================== 23:10:33.819156 | 4251a59b-b66b-41ce-a211-0373479db019 ==============================
[0m23:10:33.819156 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:10:33.820130 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m23:10:33.832310 [info ] [MainThread]: dbt version: 1.9.8
[0m23:10:33.833310 [info ] [MainThread]: python version: 3.12.8
[0m23:10:33.834275 [info ] [MainThread]: python path: C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\.venv\Scripts\python.exe
[0m23:10:33.834275 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m23:10:33.889210 [info ] [MainThread]: Using profiles dir at C:\Users\Uso Pessoal\.dbt
[0m23:10:33.890221 [info ] [MainThread]: Using profiles.yml file at C:\Users\Uso Pessoal\.dbt\profiles.yml
[0m23:10:33.890221 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\dbt_project.yml
[0m23:10:33.891371 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m23:10:33.892496 [debug] [MainThread]: Command `dbt debug` failed at 23:10:33.892496 after 0.29 seconds
[0m23:10:33.892496 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257903F9A60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002579176C0E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257906F3E30>]}
[0m23:10:33.893548 [debug] [MainThread]: Flushing usage events
[0m23:10:35.355700 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:11:15.836343 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6EC47380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6EC46870>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6EC47440>]}


============================== 23:11:15.841641 | b47d0ecc-8804-43f5-a71a-08c48518c64c ==============================
[0m23:11:15.841641 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:11:15.842946 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug --config-dir', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:11:15.854463 [info ] [MainThread]: To view your profiles.yml file, run:

start C:\Users\Uso Pessoal\.dbt
[0m23:11:15.855574 [debug] [MainThread]: Command `dbt debug` succeeded at 23:11:15.855574 after 0.15 seconds
[0m23:11:15.856736 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6C6EA2A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6F6EECF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6F6ECAD0>]}
[0m23:11:15.856736 [debug] [MainThread]: Flushing usage events
[0m23:11:17.130185 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:12:55.248653 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016731585370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016732203E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016731E7B2F0>]}


============================== 23:12:55.255670 | 248e466f-23fc-4c1a-ad7e-f120be315f58 ==============================
[0m23:12:55.255670 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:12:55.256673 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug --log-level debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:12:55.270274 [info ] [MainThread]: dbt version: 1.9.8
[0m23:12:55.271299 [info ] [MainThread]: python version: 3.12.8
[0m23:12:55.272576 [info ] [MainThread]: python path: C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\.venv\Scripts\python.exe
[0m23:12:55.273580 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m23:12:55.339985 [info ] [MainThread]: Using profiles dir at C:\Users\Uso Pessoal\.dbt
[0m23:12:55.339985 [info ] [MainThread]: Using profiles.yml file at C:\Users\Uso Pessoal\.dbt\profiles.yml
[0m23:12:55.341166 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\dbt_project.yml
[0m23:12:55.342278 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m23:12:55.343375 [debug] [MainThread]: Command `dbt debug` failed at 23:12:55.342636 after 0.32 seconds
[0m23:12:55.343731 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000167325CBBF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016732072330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016731967BC0>]}
[0m23:12:55.344773 [debug] [MainThread]: Flushing usage events
[0m23:12:57.253518 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:16:16.243708 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CBBB1DFB30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CBBB90AEA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CBBB8740B0>]}


============================== 23:16:16.249726 | 3f7c20ae-36d7-480d-a5a5-e3ea51cb84a3 ==============================
[0m23:16:16.249726 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:16:16.250132 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m23:16:16.262372 [info ] [MainThread]: dbt version: 1.9.8
[0m23:16:16.263710 [info ] [MainThread]: python version: 3.12.8
[0m23:16:16.265201 [info ] [MainThread]: python path: C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\.venv\Scripts\python.exe
[0m23:16:16.266200 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m23:16:16.325752 [info ] [MainThread]: Using profiles dir at C:\Users\Uso Pessoal\.dbt
[0m23:16:16.325752 [info ] [MainThread]: Using profiles.yml file at C:\Users\Uso Pessoal\.dbt\profiles.yml
[0m23:16:16.326749 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\dbt_project.yml
[0m23:16:16.327500 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m23:16:16.327883 [debug] [MainThread]: Command `dbt debug` failed at 23:16:16.327883 after 0.52 seconds
[0m23:16:16.328933 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CBBB90AEA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CBBCC77BF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CBBBBCD2B0>]}
[0m23:16:16.329480 [debug] [MainThread]: Flushing usage events
[0m23:16:17.339956 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:16:40.815310 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017FB8249DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017FBA7AFBC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017FB8784E60>]}


============================== 23:16:40.820355 | 80ceeac2-927c-405f-8b48-7cecb5339266 ==============================
[0m23:16:40.820355 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:16:40.821318 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:16:40.835788 [info ] [MainThread]: dbt version: 1.9.8
[0m23:16:40.835788 [info ] [MainThread]: python version: 3.12.8
[0m23:16:40.836864 [info ] [MainThread]: python path: C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\.venv\Scripts\python.exe
[0m23:16:40.836864 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m23:16:40.918565 [info ] [MainThread]: Using profiles dir at C:\Users\Uso Pessoal\.dbt
[0m23:16:40.919527 [info ] [MainThread]: Using profiles.yml file at C:\Users\Uso Pessoal\.dbt\profiles.yml
[0m23:16:40.919527 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\dbt_project.yml
[0m23:16:40.920552 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m23:16:40.920552 [debug] [MainThread]: Command `dbt debug` failed at 23:16:40.920552 after 0.23 seconds
[0m23:16:40.922078 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017FBAC58D70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017FBA941070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017FBC8BC110>]}
[0m23:16:40.922078 [debug] [MainThread]: Flushing usage events
[0m23:16:41.615799 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:17:08.338845 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191EF665280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191EFF7AAE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191ED6DB6B0>]}


============================== 23:17:08.344884 | 6572e5ce-7196-4695-b32c-8e29be07534e ==============================
[0m23:17:08.344884 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:17:08.344884 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:17:08.359845 [info ] [MainThread]: dbt version: 1.9.8
[0m23:17:08.360843 [info ] [MainThread]: python version: 3.12.8
[0m23:17:08.360843 [info ] [MainThread]: python path: C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\.venv\Scripts\python.exe
[0m23:17:08.361898 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m23:17:08.419908 [info ] [MainThread]: Using profiles dir at C:\Users\Uso Pessoal\.dbt
[0m23:17:08.421259 [info ] [MainThread]: Using profiles.yml file at C:\Users\Uso Pessoal\.dbt\profiles.yml
[0m23:17:08.421259 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\dbt_project.yml
[0m23:17:08.422424 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m23:17:08.423168 [debug] [MainThread]: Command `dbt debug` failed at 23:17:08.423168 after 0.22 seconds
[0m23:17:08.423168 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191EF665280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191F01C3110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191EFAA9070>]}
[0m23:17:08.424418 [debug] [MainThread]: Flushing usage events
[0m23:17:09.051206 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:17:45.424161 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000286A6B09D30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000286A9A5EE70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000286A99FED50>]}


============================== 23:17:45.429200 | a54c1da4-9347-4a26-98d5-58d144e04e7b ==============================
[0m23:17:45.429200 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:17:45.430216 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:17:45.443717 [info ] [MainThread]: dbt version: 1.9.8
[0m23:17:45.444817 [info ] [MainThread]: python version: 3.12.8
[0m23:17:45.444817 [info ] [MainThread]: python path: C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\.venv\Scripts\python.exe
[0m23:17:45.445828 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m23:17:45.504542 [info ] [MainThread]: Using profiles dir at C:\Users\Uso Pessoal\.dbt
[0m23:17:45.505050 [info ] [MainThread]: Using profiles.yml file at C:\Users\Uso Pessoal\.dbt\profiles.yml
[0m23:17:45.505745 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\dbt_project.yml
[0m23:17:45.506261 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m23:17:45.507647 [debug] [MainThread]: Command `dbt debug` failed at 23:17:45.507647 after 0.21 seconds
[0m23:17:45.507647 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000286A91C2AE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000286A96D2780>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000286AB250470>]}
[0m23:17:45.507647 [debug] [MainThread]: Flushing usage events
[0m23:17:46.319893 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:45:33.759577 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269119F6E40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026911632A20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002691103F890>]}


============================== 23:45:33.765605 | 462e5b79-d33c-4a39-bf26-8e2c7392046c ==============================
[0m23:45:33.765605 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:45:33.766576 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m23:45:33.779576 [info ] [MainThread]: dbt version: 1.9.8
[0m23:45:33.780577 [info ] [MainThread]: python version: 3.12.8
[0m23:45:33.781579 [info ] [MainThread]: python path: C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\.venv\Scripts\python.exe
[0m23:45:33.782576 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m23:45:33.839075 [info ] [MainThread]: Using profiles dir at C:\Users\Uso Pessoal\.dbt
[0m23:45:33.839809 [info ] [MainThread]: Using profiles.yml file at C:\Users\Uso Pessoal\.dbt\profiles.yml
[0m23:45:33.839809 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\dbt_project.yml
[0m23:45:33.841023 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m23:45:33.842175 [debug] [MainThread]: Command `dbt debug` failed at 23:45:33.842175 after 0.28 seconds
[0m23:45:33.842175 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002691171C1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026910FE5850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002690E0360F0>]}
[0m23:45:33.843155 [debug] [MainThread]: Flushing usage events
[0m23:45:34.662663 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:48:42.933573 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C52548F6B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C52656BE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C52656BE30>]}


============================== 23:48:42.938664 | 4428dd88-e31b-4309-a349-ab83bc23829d ==============================
[0m23:48:42.938664 [info ] [MainThread]: Running with dbt=1.9.8
[0m23:48:42.939626 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Uso Pessoal\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:48:42.953668 [info ] [MainThread]: dbt version: 1.9.8
[0m23:48:42.954722 [info ] [MainThread]: python version: 3.12.8
[0m23:48:42.955643 [info ] [MainThread]: python path: C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\.venv\Scripts\python.exe
[0m23:48:42.955643 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m23:48:43.014052 [info ] [MainThread]: Using profiles dir at C:\Users\Uso Pessoal\.dbt
[0m23:48:43.014052 [info ] [MainThread]: Using profiles.yml file at C:\Users\Uso Pessoal\.dbt\profiles.yml
[0m23:48:43.015016 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\dbt_project.yml
[0m23:48:43.019882 [info ] [MainThread]: adapter type: postgres
[0m23:48:43.019882 [info ] [MainThread]: adapter version: 1.9.0
[0m23:48:43.021006 [info ] [MainThread]: Configuration:
[0m23:48:43.021988 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m23:48:43.021988 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m23:48:43.023268 [info ] [MainThread]: Required dependencies:
[0m23:48:43.024289 [debug] [MainThread]: Executing "git --help"
[0m23:48:43.063865 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m23:48:43.063865 [debug] [MainThread]: STDERR: "b''"
[0m23:48:43.064906 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m23:48:43.064906 [info ] [MainThread]: Connection:
[0m23:48:43.065865 [info ] [MainThread]:   host: localhost
[0m23:48:43.065865 [info ] [MainThread]:   port: 5432
[0m23:48:43.066868 [info ] [MainThread]:   user: postgres
[0m23:48:43.066868 [info ] [MainThread]:   database: Northwind
[0m23:48:43.067891 [info ] [MainThread]:   schema: public
[0m23:48:43.067891 [info ] [MainThread]:   connect_timeout: 10
[0m23:48:43.068904 [info ] [MainThread]:   role: None
[0m23:48:43.068904 [info ] [MainThread]:   search_path: None
[0m23:48:43.070002 [info ] [MainThread]:   keepalives_idle: 0
[0m23:48:43.070002 [info ] [MainThread]:   sslmode: None
[0m23:48:43.071137 [info ] [MainThread]:   sslcert: None
[0m23:48:43.072143 [info ] [MainThread]:   sslkey: None
[0m23:48:43.073154 [info ] [MainThread]:   sslrootcert: None
[0m23:48:43.073154 [info ] [MainThread]:   application_name: dbt
[0m23:48:43.074190 [info ] [MainThread]:   retries: 1
[0m23:48:43.075581 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m23:48:43.362453 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m23:48:43.520986 [debug] [MainThread]: Using postgres connection "debug"
[0m23:48:43.520986 [debug] [MainThread]: On debug: select 1 as id
[0m23:48:43.520986 [debug] [MainThread]: Opening a new connection, currently in state init
[0m23:48:43.639215 [debug] [MainThread]: SQL status: SELECT 1 in 0.118 seconds
[0m23:48:43.640354 [debug] [MainThread]: On debug: Close
[0m23:48:43.640354 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m23:48:43.641351 [info ] [MainThread]: [31m1 check failed:[0m
[0m23:48:43.642316 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Uso Pessoal\Desktop\Estudos\Projeto Analise Dados\Projeto_Northwind\dbt_project.yml> not found

[0m23:48:43.643321 [debug] [MainThread]: Command `dbt debug` failed at 23:48:43.643321 after 0.91 seconds
[0m23:48:43.643321 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m23:48:43.644321 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C52548F6B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C52A8118E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C52AB225A0>]}
[0m23:48:43.645321 [debug] [MainThread]: Flushing usage events
[0m23:48:44.293826 [debug] [MainThread]: An error was encountered while trying to flush usage events
